# Default Configuration
# Profil aktif default adalah 'local'
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Pastikan aplikasi membaca port dari environment (penting untuk Back4App)
server.port=${PORT:8080}

# Konfigurasi Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:lingz_finance_bot}
