# Default Configuration
# Profil aktif default adalah 'local'
spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}

# Konfigurasi Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:lingz_finance_bot}
