# Database Configuration (H2 File based for local dev, avoid needing posgtres installation)
spring.datasource.url=jdbc:h2:file:./data/money_tracking;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Telegram Bot Configuration
telegram.bot.token=${TELEGRAM_BOT_TOKEN:dummy}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:dummy}
